apiVersion: v1
kind: ConfigMap
metadata:
  name: aimqwen38flash-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: aimqwen38flash
    app.kubernetes.io/managed-by: Helm
data:
  CTX_SIZE: "{{ .Values.env.CTX_SIZE }}"
  THREADS: "{{ .Values.env.THREADS }}"
  PARALLEL: "{{ .Values.env.PARALLEL }}"
  MODEL_ALIAS: "{{ .Values.env.MODEL_ALIAS }}"
  NGPU_LAYERS: "{{ .Values.env.NGPU_LAYERS }}"
  N_CPU_MOE: "{{ .Values.env.N_CPU_MOE }}"
  SPEC_TYPE: "{{ .Values.env.SPEC_TYPE }}"
  DRAFT_MAX: "{{ .Values.env.DRAFT_MAX }}"
  DRAFT_NGL: "{{ .Values.env.DRAFT_NGL }}"
  DRAFT_THREADS: "{{ .Values.env.DRAFT_THREADS }}"
  DRAFT_FILE: "{{ .Values.env.DRAFT_FILE }}"
  BATCH_SIZE: "{{ .Values.env.BATCH_SIZE }}"
  UBATCH_SIZE: "{{ .Values.env.UBATCH_SIZE }}"
  CACHE_TYPE_K: "{{ .Values.env.CACHE_TYPE_K }}"
  CACHE_TYPE_V: "{{ .Values.env.CACHE_TYPE_V }}"
